/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#060e20",
        "surface-dim": "#060e20",
        "surface-container": "#0c1934",
        "surface-container-low": "#081329",
        "surface-container-high": "#101e3e",
        "surface-container-highest": "#142449",
        "surface-bright": "#172b54",
        "surface-variant": "#142449",
        "surface-container-lowest": "#000000",
        "primary": "#9d8fff",
        "primary-dim": "#7157ff",
        "primary-container": "#5628fe",
        "primary-fixed": "#c2b9ff",
        "primary-fixed-dim": "#b4a9ff",
        "secondary": "#b4d400",
        "secondary-dim": "#a7c500",
        "secondary-fixed": "#d8fe00",
        "secondary-container": "#212900",
        "tertiary": "#a1faff",
        "tertiary-dim": "#00e5ee",
        "tertiary-container": "#00f4fe",
        "error": "#fd6f85",
        "error-container": "#8a1632",
        "on-surface": "#dee5ff",
        "on-surface-variant": "#9baad6",
        "on-background": "#dee5ff",
        "on-primary": "#1d0071",
        "on-primary-container": "#f6f1ff",
        "on-primary-fixed": "#240086",
        "on-primary-fixed-variant": "#4000d7",
        "on-secondary": "#394500",
        "on-secondary-container": "#94af00",
        "on-tertiary": "#006165",
        "on-tertiary-container": "#00575b",
        "on-error": "#490013",
        "on-error-container": "#ff97a3",
        "outline": "#65759e",
        "outline-variant": "#38476d",
        "background": "#060e20",
        "inverse-surface": "#faf8ff",
        "inverse-primary": "#5628fe",
        "inverse-on-surface": "#4d556b",
        "surface-tint": "#9d8fff",
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}
