import { useState, useEffect } from 'react'
import useManifest from '@/hooks/useManifest'
import QuizCard from '@/components/QuizCard'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Progress } from '@/components/ui/progress'
import { Badge } from '@/components/ui/badge'
import { HelpCircle, RotateCcw, Trophy } from 'lucide-react'

function shuffleArray(arr) {
  const shuffled = [...arr]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

export default function QuizPage() {
  const { manifest, loading: manifestLoading, error: manifestError } = useManifest()
  const [questions, setQuestions] = useState(null)
  const [totalQuestions, setTotalQuestions] = useState(0)
  const [loadingQuiz, setLoadingQuiz] = useState(false)
  const [quizError, setQuizError] = useState(null)
  const [currentIndex, setCurrentIndex] = useState(0)
  const [score, setScore] = useState(0)
  const [answered, setAnswered] = useState(0)

  useEffect(() => {
    if (!manifest?.quizPath) return

    let cancelled = false
    setLoadingQuiz(true)

    async function loadQuiz() {
      try {
        const res = await fetch('/' + manifest.quizPath)
        if (!res.ok) throw new Error(`Failed to load quiz: ${res.status}`)
        const data = await res.json()
        const questionArray = data.questions || []
        if (!cancelled) {
          setTotalQuestions(data.totalQuestions || questionArray.length)
          setQuestions(shuffleArray(questionArray))
          setLoadingQuiz(false)
        }
      } catch (err) {
        if (!cancelled) {
          setQuizError(err.message)
          setLoadingQuiz(false)
        }
      }
    }

    loadQuiz()
    return () => { cancelled = true }
  }, [manifest?.quizPath])

  const handleNext = () => {
    // Check if current question was answered correctly
    setAnswered((a) => a + 1)
    setCurrentIndex((i) => i + 1)
  }

  const restart = () => {
    setQuestions(shuffleArray(questions))
    setCurrentIndex(0)
    setScore(0)
    setAnswered(0)
  }

  if (manifestLoading || loadingQuiz) {
    return (
      <div className="flex items-center justify-center py-20">
        <p className="text-muted-foreground animate-pulse">Loading quiz questions...</p>
      </div>
    )
  }

  if (manifestError || quizError) {
    return (
      <div className="flex items-center justify-center py-20">
        <p className="text-destructive">Error: {manifestError || quizError}</p>
      </div>
    )
  }

  if (!questions || questions.length === 0) {
    return (
      <div className="max-w-2xl mx-auto">
        <h1 className="text-2xl font-bold mb-6">Practice Quiz</h1>
        <Card>
          <CardContent className="py-16 text-center space-y-4">
            <HelpCircle className="size-12 mx-auto text-muted-foreground/50" />
            <p className="text-lg font-medium text-muted-foreground">No quiz questions available yet</p>
            <p className="text-sm text-muted-foreground/70">
              Quiz questions will appear here once generated by the pipeline.
            </p>
          </CardContent>
        </Card>
      </div>
    )
  }

  // Quiz complete
  if (currentIndex >= questions.length) {
    return (
      <div className="max-w-2xl mx-auto space-y-6">
        <h1 className="text-2xl font-bold">Practice Quiz</h1>
        <Card>
          <CardContent className="py-12 text-center space-y-6">
            <Trophy className="size-16 mx-auto text-primary" />
            <div className="space-y-2">
              <h2 className="text-2xl font-bold">Quiz Complete!</h2>
              <p className="text-muted-foreground">
                You answered {answered} of {questions.length} questions.
              </p>
            </div>
            <Button onClick={restart} variant="outline">
              <RotateCcw className="size-4 mr-2" />
              Restart Quiz
            </Button>
          </CardContent>
        </Card>
      </div>
    )
  }

  const progress = (currentIndex / questions.length) * 100

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Practice Quiz</h1>
        <Badge variant="outline">
          {totalQuestions} total questions
        </Badge>
      </div>

      {/* Progress */}
      <div className="space-y-2">
        <div className="flex justify-between text-sm text-muted-foreground">
          <span>Question {currentIndex + 1} of {questions.length}</span>
          <span>{answered} answered</span>
        </div>
        <Progress value={progress} className="h-2" aria-label="Quiz progress" />
      </div>

      {/* Current Question */}
      <QuizCard
        key={currentIndex}
        question={questions[currentIndex]}
        onNext={handleNext}
        questionNumber={currentIndex + 1}
        totalQuestions={questions.length}
      />
    </div>
  )
}
